/* 管理後台設定（非機密）：後端 API 網址 = Apps Script 固定部署作業網址 */
window.YC_CONFIG = {
  API_URL: 'https://script.google.com/macros/s/AKfycbw8UHSKeRJP2R_ibRVM73K1yuQyDNvkg63RGVQSTPH1XbHRZ-8esWOMiBGricA-TWsHew/exec',
  /* 快速通道：閘道網址與要走閘道的查詢（閘道的路由表決定由 Cloudflare 或 Apps Script 回答）。要停用請改成 GATEWAY_ACTIONS: {} */
  GATEWAY_URL: 'https://yc-gateway.ntucpa.workers.dev/api',
  /* 發票辨識入口頁（放在公司電腦，只有公司網路或遠端連線打得開）；尚未設定時，點選單會顯示說明頁 */
  INVOICE_AI_URL: '',
  GATEWAY_ACTIONS: { getHome: 1, listCompanies: 1, listBindings: 1, listUnclassified: 1, listExceptions: 1, listIntake: 1, listCustomers: 1, customerHistory: 1, listAudit: 1, listInvites: 1, listAdmins: 1, 'tax.getBoard': 1, 'tax.openPeriod': 1, 'tax.getHome': 1, 'tax.markSeen': 1, 'tax.getNoticeList': 1, 'tax.getRecipients': 1, 'tax.saveRecipients': 1, 'tax.sendNotices': 1, 'tax.markNotified': 1, 'ai.getSettings': 1, 'ai.saveSettings': 1, 'tax.getNoticeSettings': 1, 'tax.getDocSettings': 1, 'tax.saveDocSettings': 1, 'tax.saveNoticeSettings': 1, 'tax.memoSummary': 1, 'tax.saveMemo': 1, 'tax.syncFilings': 1, 'tax.setVatExcluded': 1, 'tax.setPeriodStatus': 1, 'tax.setDeadline': 1, 'tax.markSteps': 1, 'tax.setApplicable': 1, 'tax.setNote': 1, 'tax.addFiling': 1, 'tax.listProfiles': 1, 'tax.saveProfiles': 1, 'tax.checkBills': 1, 'tax.importBill': 1, 'tax.getSettings': 1, 'tax.saveSettings': 1, 'tax.testClassify': 1, 'bank.listAliases': 1, 'bank.saveAlias': 1, 'bank.deleteAlias': 1, 'bank.bootstrapPreview': 1, 'bank.bootstrapApply': 1, 'bank.getContext': 1, 'bank.confirmMatches': 1, 'bank.cancelMatch': 1, 'bank.listRecent': 1, 'bank.suggestAliases': 1, 'bank.addAliases': 1, 'bank.getLedger': 1, 'bank.registerPayment': 1, 'bank.resolveDiff': 1, 'bank.reassignMatch': 1, 'bank.clearMarks': 1, 'bank.getAdvances': 1, 'bank.markAdvance': 1, 'bank.cancelAdvance': 1, 'bank.writeOffAdvance': 1, 'bank.getAdvanceSettings': 1, 'bank.saveAdvanceSettings': 1 }
};
